name: Publish Package

on:
    workflow_dispatch:
    release:
        types: [published]

env:
    NODE_AUTH_TOKEN: ${{ secrets.GHPR_TOKEN }}

jobs:
    deploy_release:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1

            - uses: actions/setup-node@v1
              with:
                  node-version: 16
                  registry-url: 'https://npm.pkg.github.com'

            - run: npm ci
            - run: npm run build
            - run: npm publish --access public
              
